version: '3.1'
services:
  postgres:
    container_name: notesdb
    image: postgres:13.0
    environment:
      - DEBUG=false
      - DB_EXTENSION=plpgsql,pg_trgm
      - POSTGRES_USER=resu
      - POSTGRES_PASSWORD=d0nt4get
      - POSTGRES_DB=notes
      - POSTGRES_TEST_DB=notes-test
#    volumes:
#      - ./create-test-db.sh:/docker-entrypoint-initdb.d/create-test-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resu"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
#    networks:
#      - net1

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=me@email.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

#  api:
#    container_name: api
#    privileged: true
#    build:
#      context: ./
#      dockerfile: Dockerfile-dev
#    environment:
#      - DATABASE_URL=postgresql+psycopg2://resu:d0nt4get@postgres:5432/notes
#      - DATABASE_TEST_URL=postgresql+psycopg2://resu:d0nt4get@postgres:5432/notes-test
#      - FLASK_APP=api
#      - FLASK_DEBUG=1
#      - FLASK_ENV=development
#      - APP_SETTINGS=Development
#    depends_on:
#      - postgres
#    links:
#      - postgres:postgres
#    ports:
#      - "8080:8080"
#    volumes:
#      - ".:/code"
#    networks:
#      - net1
#
#networks:
#  net1:
#    driver: bridge